AWSTemplateFormatVersion: '2010-09-09'

Resources:

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      template-file-path: ./umed_s3_buckets_cf_script.yml
      Parameters:
        Environment: devil